services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_URL: ${VITE_APP_URL:-http://localhost:9595}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-/api/auth}
    platform: linux/amd64
    ports:
      - "9595:9595"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-rss_feed}
      - DATABASE_URL=postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-rss_feed}
      - GOOLE_CLIENT_ID=${GOOLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PRODUCTION_URL=${PRODUCTION_URL}

  db:
    image: postgres:17.0
    hostname: db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_DB=${DB_NAME:-rss_feed}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
