version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "9595:9595"
    volumes:
      - .:/app
      - /app/node_modules
